### ISSUE TITLE
Could not load boilerplate, sorry.

### ISSUE THREAD

**Issue by ibigbug** [christianalfoni/webpack-bin#101]
I'm running this awesome project locally.

Trying to load an boilerplate will throw an error as titled.

It seems this was no seeding data created in mongo db after app booting, or there are something I missed?

**Comment by christianalfoni** [comment]
Yeah, it is because the boilerplates are in the database on the server :) they have special ID's, like `react`, `cerebral` etc. so you have to create your own bins really and rename their IDs to those :)

**Comment by ibigbug** [comment]
If no boilerplates found, the slide down menu should be empty I think?

**Comment by afc163** [comment]
How to create own bins locally?

**Comment by christianalfoni** [comment]
Currently boilerplates are hardcoded, will change that in later versions :)

@afc163 You create a bin by just starting the service and create code

To make it a boilerplate you have to hardcode it. 

The reason boilerplates are harcoded is because there is no "user concept", everything is open. But I do not want anyone to create boilerplates. So need a user concept first

**Comment by christianalfoni** [comment]
Closing this, please reopen if you have any more questions :)
