### ISSUE TITLE
Is www.webpackbin.com now running v2 of Webpack bin?

### ISSUE THREAD

**Issue by jamesopti** [christianalfoni/webpack-bin#233]
@christianalfoni  Awesome project you have here!

I was trying out v2 of WebpackBin on https://webpackbin-test.firebaseapp.com, attempting the same react demo you did in the youtube video, but it doesnt work for me (says packages are still loading).

Is webpackbin.com now running v2? I know the youtube video was from early February.

Thanks!

**Comment by christianalfoni** [comment]
@jamesopti Hi there, www.webpackbin.com is now running on v2 :)

There has been some stability issues due to a new architecture that works really well when it works, but there are some edge cases that is hard to track down. Have some vacation time in a week so will have a review of architecture to optimize bundling fetching. 

Let me know if this happen in production though!

**Comment by jamesopti** [comment]
Thanks @christianalfoni ! Will close this ticket then.
