### ISSUE TITLE
toolbar blinks on boilerplate switch

### ISSUE THREAD

**Issue by Guria** [christianalfoni/webpack-bin#25]

**Comment by christianalfoni** [comment]
Hm, yeah, it is because the BIN is run and I do not want you to click anything else while waiting for a response. Thing is that it is crazy fast... hehe... maybe I should just prevent clicks, not indicate it with lowering the opacity. What you think?

**Comment by RamonGebben** [comment]
I think that is the best way to go for now. 
If you do want to communicate that the user is not allowed to click, I would apply a full screen overlay with a "Loading your boilerplate" or something, maybe somebody has a very flaky connection and might take a bit longer to load that's why I would go for the overlay solution.

**Comment by christianalfoni** [comment]
Yeah, I agree. Its actually really problematic when things go too fast :) Let me insert a delay of a second there to allow the overlay to fade in and out naturally. And when things takes longer it will just fade out later...

**Comment by christianalfoni** [comment]
Just disabling the styles causing the blink for now, loading boilerplates is just a few kb. Just takes more time creating the overlay, and there is so much to do ;-) Can look into it later if it becomes an issue
