### ISSUE TITLE
Google instant style npm package search

### ISSUE THREAD

**Issue by bfitch** [christianalfoni/webpack-bin#48]
Would be awesome to see a list of filtered list of npm packages as you search. Right now there is no UI feedback until you hit enter.

![screen shot 2016-03-09 at 11 58 35 pm](https://cloud.githubusercontent.com/assets/577208/13659892/68e85088-e653-11e5-97cc-39625a7e8667.png)

![screen shot 2016-03-10 at 12 00 23 am](https://cloud.githubusercontent.com/assets/577208/13659895/7607d16c-e653-11e5-93f0-5454ce9ecc07.png)

**Comment by christianalfoni** [comment]
this is quite challenging actually because there is no API to search for NPM packages. And the search on `npmjs.org` is actually pretty crappy. What I could though is have "quick result" on packages that are already in the database. So for example searching "lo" would instantly bring up lodash because it is in the database already. Seems okay?

**Comment by bfitch** [comment]
Yeah! That seems like a great first step. 😀

**Comment by RamonGebben** [comment]
Well since you added the example of the Google address bar. This uses a cashed list if stuff which used more often, so what we would do is save each save query of all the users and apply a rating system to this to get a top 100 of most searched packages. This we can use to fake an "auto complete". What do you guys think?

**Comment by rtsao** [comment]
https://github.com/solids/npmsearch aka http://npmsearch.com has an API you could use. It has more advanced ranking heuristics as well.

**Comment by christianalfoni** [comment]
Thanks @rtsao , let me check that first :)

**Comment by christianalfoni** [comment]
Hm, I am having second thoughts on this. Like searching for "react" does not give you react as a result. I think it will be quite confusing to use it as we would have to still allow you to add react specifically even though it is not part of search result. This is also stretching the scope of webpackbin. It is not really intended to be a tool to find new NPM packages. I think google does a far better job at that than what webpackbin could ever do. It is really weird that the search is not based on actual package name "hit"... hm

So yeah, my current stand on this is that users of webpackbin already knows what packages they want to play with or they arrive at the site because of a link to an existing bin with existing packages.

Please push back on this if you disagree :-)

**Comment by bfitch** [comment]
Yeah totally understand. :) The use case I saw was more from a UX perspective-- that you don't receive any feedback about what you are typing until you hit 'Enter'.  So it's not totally necessary to implement a full fuzzy search with instant feedback. I was just confused initially how to even install a package. But, I think that can be solved more easily.

Also, perhaps a better way to solve the UX problem was the other feature request for auto importing packages via `require('foo');` or `import 'foo' from foo;` in the code editor a la esnext bin.

**Comment by christianalfoni** [comment]
Yeah, definitely. Lets focus on that auto-import first at least :-)
