### ISSUE TITLE
Error on importing nested modules

### ISSUE THREAD

**Issue by yelouafi** [christianalfoni/webpack-bin#64]
When I try to import a nested module

``` javascript
import { take } from 'redux-saga/effects'
```

I get this error

```
Module not found: Error: Cannot resolve module 'redux-saga/effects' in  
/api/sandbox/14576875261374994
```

**Comment by christianalfoni** [comment]
Yes,

Webpackbin does not currently support entry points not listed in the `package.json` file.

I have an issue on it here: https://github.com/webpack/webpack/issues/2159

The thing is that the DLLPlugin creates a manifest of entry points, but it is only based on traversing from the "main" path in the `package.json` file.

I have tried to get around it, but have not figured it out yet. Hopefully @sokra will give some insight to it. It is possible, I am sure, its just a matter of how :-)

But thanks for creating the issue, motivates me to "hack" some more on it.

**Comment by yelouafi** [comment]
thanks for the reply (and also for webpack-bin, great site BTW!)

Can we get around this by adding some `webpack-bin` entry on package.json for example ?

**Comment by christianalfoni** [comment]
Glad you like it! And great work on Redux Saga btw! :)

After my initial tries on getting it to work I think it is an internal webpack thing.

Let me reason about it with you now:
1. WepbackBin creates a Webpack compiler for `redux-saga` (+ React + Redux etc.)
2. The entry points to the bundle are the "main" paths from the different package.json files
3. Webpack traverses these "main" entry points and creates a `manifest.json` file containing all files that can be required based on this "main" traversal
4. Webpack bundles it up

So what I believe the problem is here is that because Webpack can not find f.ex. `redux-saga/effects` from the "main" path it is not included in the bundle. So even if I manually write that path to the `manifest.json` file it just does not exist

So with an extra field in package.json would indeed help in terms of creating multiple entry points for the bundle, but I am not sure if an entry point can be named: 

``` js
entry: {
  'redux-saga/effects': 'redux-saga/effects'
}
```

Maybe it does work? Just have to pee, let me create a proof of concept of that when I get back ;-)

That would indeed be a nice fix and I think it really should be part of `package.json` so that consumers of the package knows what entry points are to be used in the library

**Comment by christianalfoni** [comment]
Okay, I figured it out :-)

There are a couple of approaches here. We could do:

``` js
{
  "webpackbin": {
    "entries": {
      "redux-saga": "lib/index.js",
      "redux-saga/effects": "lib/effects.js"
    }
  }
}
```

And so on...

That is enough for WebpackBin to understand the entry points. Also opens up for other kinds of options later, which is nice.

But the alternative is that I just make every JS file an entry point automatically and use commonschunkplugin to make sure there is no duplicate modules. That way you do not need to configure anything and you would be able to require any JS file on any path in the package.

But doing so has the potential of bringing in lots of unnecessary stuff as well. Making the bundle bigger, like including dists etc. Like the Angular2 package would be a complete mess with this approach.

But with package.json approach we can also temporarily define these paths in WebpackBin itself, until authors gets them into their package.json file. It is a lot cleaner, but requires more maintenance.  

what do you think?

**Comment by Guria** [comment]
Ask package authors to support another field for 3rd party service to work? Don't think it would be accepted and will get much spread. Just imagine how this field would look in lodash and angular2.

**Comment by christianalfoni** [comment]
Yeah, I worry about that as well. But like Angular 2 includes all the bundles in their built package, in different versions. The WebpackBin bundle will be huge.

Can of course ignore paths like `dist`, `bundles` etc. but that is not really safe.

There is also a different approach. Both Lodash and Redux-Saga exposes all their methods on the main entry as well. Which means Webpack builds up the manifest correctly. What I can do is traverse the manifest instead and expose the single files resolved by webpack.

That would not fix Angular2, and other packages with missing `main`, but it will fix lodash, redux-saga etc.

**Comment by christianalfoni** [comment]
Okay, I decided to implement this approach now as it makes sense. Have to think more about angular2, might have to make a specific implementation for it. But next up we can use nested paths :)

**Comment by christianalfoni** [comment]
Hmf... crap, lodash does not require its `lodash/array` from the `lodash.js` file. It is its own built file... how weird.

Only way to solve this is to treat all `.js` files as an entry point. But this is risky as it will include files not needed in all packages really. Angular2 package would be like 20MB.

There is an other way to handle this actually. Going back to the initial suggestion:

``` js
{
  "webpackbin": {
    "entryDirs": []
  }
}
```

By default WebpackBin will find all files in the directory stated in the `main` property. So for example with `redux-saga` where entry is `lib/index.js` it will make all `.js` files in `lib` folder an entry point. Or by default all `.js` files in the root.

That means Angular2 just needs this:

``` js
{
  "webpackbin": {
    "entryDirs": ['platform']
  }
}
```

Lodash needs:

``` js
{
  "webpackbin": {
    "entryDirs": ['fp']
  }
}
```

Redux saga does not need anything. That means it is also manageable to handle this manually inside WebpackBin if someone reports a package having this issue.

**Comment by christianalfoni** [comment]
Okay, tested this now and I think this will work :)
