### ISSUE TITLE
Cerebral boilerplate is broken

### ISSUE THREAD

**Issue by Guria** [christianalfoni/webpack-bin#94]
`Uncaught TypeError: Cannot read property 'call' of undefined`

**Comment by christianalfoni** [comment]
Hm, this does not happen on my end? Did you do something first? It seems to be in regards of loading up the vendors bundle. That error appears when things are not loaded correctly.

It might be because you have the old version of the bundle. I had to make some changes to it. So clear your cache and try again :)

**Comment by Guria** [comment]
Still the same error.
http://pastebin.com/rDnevEy2

**Comment by Guria** [comment]
It was cache stuff. Works now.

**Comment by christianalfoni** [comment]
Great! :+1:
