### ISSUE TITLE
Require fails for "nested" modules

### ISSUE THREAD

**Issue by avanslaars** [christianalfoni/webpack-bin#96]
Attempting to run some simple code using Snabbdom works until I try to require one of its modules. This code works in my standard environment but when trying to run through webpackbin, the error message says it cannot find the module: **ERROR: ModuleNotFoundError**

```
const snabbdom = require('snabbdom')
const h = require('snabbdom/h')
const marked = require('marked')

const patch = snabbdom.init([
  require('snabbdom/modules/props')
])
const markdown = marked('# Hey There')
const newNode = h('div',{props:{innerHTML:markdown}},[])

patch(document.querySelector('#app'), newNode)
```

The call to `require('snabbdom/modules/props')` is the offending line. The call to `require('snabbdom/h')` works as expected. I also attempted to run the require for the props module at the top of the code and use the assigned const and that didn't seem to make a difference. The bin in question can be found here: [http://www.webpackbin.com/4J4Xq7F6g](http://www.webpackbin.com/4J4Xq7F6g).

**Comment by christianalfoni** [comment]
Yes, this is due to optimizations. WebpackBin currently needs to know where the entrypoints are. With `package.json` you only define one entry point, but WebpackBin has become a bit smarter and traverses the folder of the appointed `main` entry file and finds the rest of them, but it does not go deeper into the folder structure. Many libraries has lots of bundles etc. included in their package, that should not be part of the build. Like doing this on `angular2` would cause the vendors bundle to be several megabytes.

For now WebpackBin needs to know about these "sub-directories" and these are added as necessary. Like `angular2` and `lodash` currently has their sub-directories listed inside webpackbin, which is just `platform` on angular2 and `fp` on lodash. I can add `modules` on snabbdom :)

I hope to encourage library authors to add a webpackbin property to their package.json where they list the directories of where entry points are located.

But let me add `modules` as a sub-directory to snabbdom. Are there any other sub-folders there you know of?

**Comment by avanslaars** [comment]
Understood and thanks for the instant reply!! All of the modules for Snabbdom that I am aware of are in that modules folder... that and obviously, the `h` module, which was already working. I really appreciate it :)

**Comment by christianalfoni** [comment]
Okay, cool, I will add `modules` for next release. Thanks so much for reporting :-)

**Comment by afc163** [comment]
http://www.webpackbin.com/EyLnkfcpg

same issue for `import 'antd/lib/index.css'`

**Comment by christianalfoni** [comment]
Cool, added `antd` as well, ready for next release... right around the corner
